services:

  algorithms:
    build:
      context: ./docker/algorithms
      args:
        CARLA_VERSION: ${CARLA_VERSION}
    image: carla-algorithms:latest
    container_name: algorithms
    env_file:
      - .env
    environment:
      - DISPLAY
      - SDL_VIDEODRIVER
    volumes:
      - ./algorithms:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/root/.Xauthority:ro
    ports:
      - "9090:9090"
    networks:
      - carla-net
  
  carla:
    build:
      context: ./docker/carla
      args:
        CARLA_VERSION: ${CARLA_VERSION}
    container_name: carla
    image: carla-simulator:latest
    environment:
      - CARLA_VERSION
      - DISPLAY
      - SDL_VIDEODRIVER
      - NVIDIA_VISIBLE_DEVICES
      - CARLA_QUALITY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/root/.Xauthority:ro
    networks:
      - carla-net
    ports:
      - "2000-2002:2000-2002"
    # Only include NVIDIA runtime if GPU is available
    runtime: ${NVIDIA_RUNTIME:-runc}

networks:
  carla-net:
    driver: bridge
