services:
  carla:
    build:
      context: ./docker/carla
      args:
        CARLA_VERSION: ${CARLA_VERSION}
    image: carla-simulator:${CARLA_VERSION}
    container_name: carla
    environment:
      - SDL_VIDEODRIVER=offscreen
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - carla-net
    ports:
      - "2000-2002:2000-2002"

  algorithms:
    build:
      context: ./docker/algorithms
      args:
        CARLA_VERSION: ${CARLA_VERSION}
    image: carla-algorithms:latest
    container_name: algorithms
    volumes:
      - ~/.ssh:/root/.ssh:ro  # Mount the entire SSH directory to access keys
      - ${SSH_AUTH_SOCK}:/ssh-agent  # Bind SSH socket
      - ${DOCKER_SOCKET}:/var/run/docker.sock 
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file:
      - .env
    environment:
      - SSH_AUTH_SOCK=/ssh-agent  # Match the mount path
      - CARLA_HOST=carla
      - DISPLAY=${DISPLAY}
    networks:
      - carla-net
  
networks:
  carla-net:
    driver: bridge
