services:
  algorithms:
    build:
      context: ./docker/algorithms
      network: host
      args:
        CARLA_VERSION: ${CARLA_VERSION}
    image: carla-algorithms:latest
    container_name: algorithms
    env_file:
      - .env
    environment:
      CARLA_VERSION: ${CARLA_VERSION}
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTHORITY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      VK_LAYER_PATH: /usr/share/vulkan/explicit_layer.d
    volumes:
      - ./algorithms:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
  
  carla:
    build:
      context: ./docker/carla
      network: host
      args:
        CARLA_VERSION: ${CARLA_VERSION}
    container_name: carla
    image: carla-simulator:latest
    environment:
      CARLA_VERSION: ${CARLA_VERSION}
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTHORITY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      VK_LAYER_PATH: /usr/share/vulkan/explicit_layer.d
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/dri:/dev/dri
      - ${XAUTHORITY}:${XAUTHORITY}
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
      - /usr/share/vulkan/explicit_layer.d:/usr/share/vulkan/explicit_layer.d
    runtime: nvidia
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
